### ISSUE TITLE
The current official website knowage related problems

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-knowage#4]
## Language

- [x] Chinese
- [x] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: 
* Description: 
1.已经更换使用mariadb数据库了。
2.根据文档，修改密码修改不了
* Screenshot
![image](https://user-images.githubusercontent.com/76861519/113674992-6de3e700-96ed-11eb-958a-63cca365841d.png)

![image](https://user-images.githubusercontent.com/76861519/113675345-d763f580-96ed-11eb-8fe0-6a3fd4fb08c9.png)

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by chendelin1982** [comment]
done
