### ISSUE TITLE
knowage 7.4 on centos on 腾讯云  页面无法初始化

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-knowage#7]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [x] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
101.34.81.253

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/123618779-157b3c00-d83b-11eb-89c0-d852b35e2961.png)

![image](https://user-images.githubusercontent.com/83911329/123618962-45c2da80-d83b-11eb-9734-3a8af781d063.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
docker-compose up  -d

start error:

```
ERROR: for knowage  Cannot start service knowage: OCI runtime create failed: invalid mount {Destination:[/home/knowage/apache-tomcat/resources] Type:bind Source:/var/lib/docker/volumes/6c3677804e0662777041a3354d3d260d4a29a2abf8811af788bcd1e6b6d8d821/_data Options:[rbind]}: mount destination [/home/knowage/apache-tomcat/resources] not absolute: unknown
ERROR: Encountered errors while bringing up the project.
```

![image](https://user-images.githubusercontent.com/63622990/123888463-2389a380-d986-11eb-8c0f-3c813345ab77.png)

**Comment by zengxc-1996** [comment]
The image is error:

![image](https://user-images.githubusercontent.com/63622990/123913980-7298fe00-d9b1-11eb-862c-2d38cd086acc.png)

**Comment by qiaofeng1227** [comment]
transfer to: https://github.com/KnowageLabs/Knowage-Server-Docker/issues/50
